### ISSUE TITLE
option for wget instead of curl

### ISSUE THREAD

**Issue by mikew** [mikew/ss-plex.bundle#10]
plexmediaserver/ubuntu doesn't work out of the box, and each update requires copying the system libcurl.so to /usr/lib/plexmediaserver.

wget supports the same functionality as curl, could be an option for those users.

**Comment by JamminR** [comment]
I'm all for "no dependencies" to make code/project life easier.
Since you're mostly using curl/wget for obtaining single files at a time, if Plex allows an off-shoot python thread that wouldn't die when someone left the SSPlex channel...couldn't python be used to grab a single file?
Just a quick google of python wget found code here http://stackoverflow.com/a/9271109

But, if Plex kills threads after leaving channel, I see your challenge.
Dumb research assistant work for you for popular Plex servers.
Linux - (my somewhat limited Linux experience indicates it's almost always 'just there' as a command line bin)
Windows - Possibly, http://gnuwin32.sourceforge.net/packages/wget.htm - seems to have it's own dependencies.
Mac - https://www.merenbach.com/software/wget/
ReadyNAS - (Seems scattered support, sharpest release I found here -) http://www.readynas.com/forum/viewtopic.php?f=48&t=33413

**Comment by mikew** [comment]
It's not Plex that kills the thread, it's an operating-system defined thing. The main thread exits after a certain delay (or maybe under higher load).

Plex channels do get access to pycurl, so there's hope of removing the external dependencies altogether. But the problem above would still remain.

Thanks so much for the research though! To add, OS X users can `brew install wget`.

**Comment by mikew** [comment]
version 0.5.0 adds support for wget
