### ISSUE TITLE
Unable to delete ss-plex downloads

### ISSUE THREAD

**Issue by kurtman1111** [mikew/ss-plex.bundle#32]
I am unable to delete anything in PMS that I have downloaded from ss-plex. "Allow clients to delete media" is enabled but when I go to PMS on my computer and try to delete anything I have downloaded I get an error message to enable "Allow clients to delete media" which is already done. The next thing I have done was to go to the actual folder on my computer and deleted the file there but it still shows it in PMS. I have tried everything I can think of like syncing, emptying trash, cleaning bundles, optimizing, debugging, and even swearing but still can't find a solution to this problem. Help... Please!

**Comment by gddeen** [comment]
Sorry for this stupid suggestion...  I notice you can change some "settings" for PMS but they don't really work until you stop the Plex server and restart it.  A simple way to do that is turn your computer
off and then back on. (So I don't have to get into how to do this on a Mac, Linux, Windows, or NAS.)

And of course ignore this comment if you've tried that.

**Comment by kurtman1111** [comment]
Thanks for your suggestion but I finally figured out what was causing my problem after all. In my troubleshooting process I went into the actual folder on my computer and deleted the media file assuming this would eliminate it in PMS but this turned out to be incorrect as it was still listed and could not be deleted. I solved this problem by copying another video, pasting it into the folder on my computer, and then renaming it the same as the video I had erased before. This allowed me to go back into PMS and delete all trace of information. I think this is a serious flaw in PMS. This software should automatically sync with these folders and should not show the presence of a video that no longer exists. Now I’ll go to the plex forum to post this issue there.

Thanks again for your input and I do not think it was stupid in any way. The only stupid suggestion is one that someone is afraid to offer in the first place.

**Comment by gddeen** [comment]
This is on purpose so you can startup pms on a nas and if it doesn't connect it won't delete your library. Also so you can move media to another folder. Add the second folder to the library and pms detects the move. Then you can delete the original folder.

On May 31, 2014, at 10:18 PM, kurtman1111 notifications@github.com wrote:

Thanks for your suggestion but I finally figured out what was causing my problem after all. In my troubleshooting process I went into the actual folder on my computer and deleted the media file assuming this would eliminate it in PMS but this turned out to be incorrect as it was still listed and could not be deleted. I solved this problem by copying another video, pasting it into the folder on my computer, and then renaming it the same as the video I had erased before. This allowed me to go back into PMS and delete all trace of information. I think this is a serious flaw in PMS. This software should automatically sync with these folders and should not show the presence of a video that no longer exists. Now I’ll go to the plex forum to post this issue there.

Thanks again for your input and I do not think it was stupid in any way. The only stupid suggestion is one that someone is afraid to offer in the first place.

**Comment by mikew** [comment]
Deleting media via the web UI and directly from the hard drive works great on my end. You have to refresh your library, but that makes sense. Anyways closing as it's not directly related to the channel.
